apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - suffix:
      name: 'SUFFIX'
      displayName: 'SUFFIX'
      required: true
  - name:
      name: 'NAME'
      displayName: 'NAME'
      required: true
      value: 'lucy-api'
  - version:
      name: 'VERSION'
      required: true
      value: 1.0
  - repo:
      name: "SOURCE_REPOSITORY_URL"
      required: true
      value: 'https://github.com/bcgov/lucy-web.git'
  - repo_ref:
      name: "SOURCE_REPOSITORY_REF"
      required: true
      value: 'dev-api'
  - context_dir:
      name: "SOURCE_CONTEXT_DIR"
      required: true
      value: "/api/api_sources"
metadata:
  creationTimestamp: null
  labels:
    app: ${}
  name: ${SUFFIX}
  namespace: 7068ad-dev
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: '${NAME}:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: app/lucy
    git:
      uri: "${SOURCE_REPOSITORY_URL}"
      ref: "${SOURCE_REPOSITORY_REF}"
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'node:9'
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: fT94ctykslmWZgzDhuWe
      type: GitHub
    - generic:
        secret: Atjvk6HAWSNz2lmpIH3q
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: >-
          node@sha256:5aa0756284c7f0222c2c16988fb58d6446427ac7ae8891aa50a2de721ef4191c
      type: ImageChange
status:
  lastVersion: 1

