kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: test
  creationTimestamp: null
parameters:
- name: IMAGE
  description: 'Image for pod'
  required: true
- name: NAME
  value: invasivesbc-api
- name: SUFFIX
  value: "-dev"
- name: VERSION
  description: Version of the application
  value: "1.0.0"
- name: CHANGE_ID
  description: Change id of the project. This will help to pull image stream
  required: true
  value: "0"
- name: DB_SERVICE_NAME
  description: 'Database service name associated  with deployment'
  required: true
- name: ENVIRONMENT
  description: Application Environment type variable
  required: true
  value: 'dev'
- name: CERTIFICATE_URL
  description: Authentication certificate urls
  required: true
  value: "https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs"
- name: CPU_REQ
  value: '500m'
- name: CPU_LIMIT
  value: '750m'
- name: MEMORY_REQ
  value: '1Gi'
- name: MEMORY_LIMIT
  value: '2Gi'
- name: REPLICAS
  value: '1'
- name: APP_PORT_DEFAULT
  value: '3001-tcp'
- name: APP_PORT_OTHER
  value: '8080-tcp'
- name: PORT
  value: '3001'
- name: DB_MIGRATION_TYPE
  value: 'refresh'
- name: DB_CLEAN_UP
  value: 'none'
- name: DB_SEED
  value: 'yes'
- name: MAILER_INFO
  value: 'invasivesbc-mailer'
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels: {}
  spec:
    containers:
    - name: test
      image: "${IMAGE}"
      command:
      - container-entrypoint
      - bash
      - "-c"
      - "npm run remote:test-temp" # TODO: Change this back to npm run remote:test once the sonarqube upgrade is done
      resources:
        limits:
          cpu: '1'
          memory: 1.5Gi
        requests:
          cpu: 500m
          memory: 512Mi
      env:
      - name: DB_HOST
        value: ${DB_SERVICE_NAME}
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            key: database-user
            name: ${DB_SERVICE_NAME}
      - name: DB_PASS
        valueFrom:
          secretKeyRef:
            key: database-password
            name: ${DB_SERVICE_NAME}
      - name: DB_DATABASE
        valueFrom:
          secretKeyRef:
            key: database-name
            name: ${DB_SERVICE_NAME}
      - name: DB_PORT
        value: "5432"
      - name: APP_CERTIFICATE_URL
        value: ${CERTIFICATE_URL}
      - name: CHANGE_VERSION
        value: ${CHANGE_ID}
      - name: ENVIRONMENT
        value: ${ENVIRONMENT}
      - name: VERSION
        value: ${VERSION}
      - name: DB_MIGRATION_TYPE
        value: ${DB_MIGRATION_TYPE}
      - name: DB_CLEAN_UP
        value: ${DB_CLEAN_UP}
      - name: DB_SEED
        value: ${DB_SEED}
      - name: TEST_RUN
        value: 'yes'
      - name: APP_EMAIL_SENDER
        valueFrom:
          secretKeyRef:
            key: sender
            name: ${MAILER_INFO}
      - name: APP_EMAIL_SENDER_PWD
        valueFrom:
          secretKeyRef:
            key: sender-password
            name: ${MAILER_INFO}
      - name: APP_EMAIL_TEST_RECEIVER
        valueFrom:
          secretKeyRef:
            key: test-receiver
            name: ${MAILER_INFO}
      - name: APP_REPORT_RECEIVER
        valueFrom:
          secretKeyRef:
            key: test-receiver-list
            name: ${MAILER_INFO}
      imagePullPolicy: Always
    restartPolicy: Never
    activeDeadlineSeconds: 900
    dnsPolicy: ClusterFirst
  status: {}
