version: "3.5"
services:
  web:
    image: "lucy-web-img"
    container_name: "lucy-web"
    build:
      context: ./lucy
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    networks:
      - web-net
    volumes:
      - ./lucy:/opt/app-root/src
networks:
  web-net:
    driver: bridge
    name: lucy-web-network
