FROM node:10

RUN apt-get update
RUN npm install -g npm@6.14.12

# Create app directory

ENV HOME_ROOT=/opt/app-root
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

# Create DIR Structure
# Temp File Structure
RUN mkdir -p ${HOME_ROOT}/temp
# Issue Files
RUN mkdir -p ${HOME_ROOT}/temp/uploads/issues

WORKDIR $HOME_ROOT

WORKDIR $HOME

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./package*.json ./

# If you are building your code for production
# RUN npm install --only=production
RUN npm set progress=false && npm ci

VOLUME ${HOME}/node_modules

VOLUME ${HOME}
ENV PATH ${HOME}/node_modules/.bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

# Bundle app source
COPY ./ .

# Remove build dir
RUN rm -rf ./dist-server

# Lint
RUN npm run test:lint

# Build
RUN npm run build

# Entrypoint 
CMD [ "npm", "run", "git:run" ]


