kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-metabase-data
  namespace: 7068ad-dev
  labels:
    app: metabase
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: netapp-block-standard
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
