kind: Template
apiVersion: v1
metadata:
  name: test
parameters:
- name: IMAGE
  description: 'Image for pod'
  required: true
- name: NAME
  value: invasivesbc-api
- name: SUFFIX
  value: "-dev"
- name: VERSION
  description: Version of the application
  value: "1.0.0"
- name: CHANGE_ID
  description: Change id of the project. This will help to pull image stream
  required: true
  value: "0"
- name: AUTH_URL
  description: Auth URL
  value: "https://dev.loginproxy.gov.bc.ca/auth/realms"
- name: REALM
  description: Auth Realm
  value: standard
- name: TEST_USER_SECRET
  description: Secret of test user profile
  value: invasivesbc-load-test-user
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels: {}
  spec:
    containers:
    - name: run
      image: ${IMAGE}
      command:
      - container-entrypoint
      - bash
      - "-c"
      - "/usr/bin/tail -f /dev/null"
      resources:
        limits:
          memory: "1Gi"
          cpu: "1000m"
      env:
        - name: AUTH_URL
          value: ${AUTH_URL}
        - name: REALM
          value: ${REALM}
        - name: TEST_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: ${TEST_USER_SECRET}
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ${TEST_USER_SECRET}
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client_id
              name: ${TEST_USER_SECRET}
        - name: REMOTE
          value: 'yes'
    restartPolicy: Never
    activeDeadlineSeconds: 900
    dnsPolicy: ClusterFirst
  status: {}
