import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import java.util.regex.Pattern

/*
 * takes in a sonarqube status json payload
 * and returns the status string
 */
def sonarGetStatus (jsonPayload) {
  def jsonSlurper = new JsonSlurper()
  return jsonSlurper.parseText(jsonPayload).projectStatus.status
}

pipeline {
    agent none
    options {
        disableResume()
    }
    stages {
        stage('Build') {
            parallel {
                stage('Build API') {
                    agent { label 'build' }
                    steps {
                        sh 'printenv'
                        script {
                            echo "API Build Pipeline"
                            def filesInThisCommitAsString = sh(script:"git diff --name-only HEAD~1..HEAD | grep -E '^api/|^/api/|^app/|^/app/' || echo -n ''", returnStatus: false, returnStdout: true).trim()
                            def hasChangesInPath = (filesInThisCommitAsString.length() > 0)
                            echo "${filesInThisCommitAsString}"
                            if (!currentBuild.rawBuild.getCauses()[0].toString().contains('UserIdCause') && !hasChangesInPath){
                                currentBuild.rawBuild.delete()
                                error("No changes detected in the path ('^api/')")
                            }
                        }
                        echo "Aborting all running jobs ..."
                        script {
                            abortAllPreviousBuildInProgress(currentBuild)
                        }
                        echo "Building ..."
                        sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run build -- --pr=${CHANGE_ID}"
                        /*sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run build-tools --pr=${CHANGE_ID}"*/
                    }

                }
                stage('Build APP') {
                    agent { label 'build' }
                    steps {
                        script {
                            echo "App Build Pipeline"
                            def filesInThisCommitAsString = sh(script:"git diff --name-only HEAD~1..HEAD | grep -E '^/app/|^app/|^api/|^/api/' || echo -n ''", returnStatus: false, returnStdout: true).trim()
                            def hasChangesInPath = (filesInThisCommitAsString.length() > 0)
                            if (!currentBuild.rawBuild.getCauses()[0].toString().contains('UserIdCause') && !hasChangesInPath){
                                currentBuild.rawBuild.delete()
                                error("No changes detected in the path ('^app/')")
                            }
                        }
                        echo "Aborting all running jobs ..."
                        script {
                            abortAllPreviousBuildInProgress(currentBuild)
                        }
                        echo "Building ..."
                        sh "cd app/.pipeline && ./npmw ci && DEBUG=* ./npmw run build -- --pr=${CHANGE_ID}"
                    }
                }
            }
        }
        stage('Pre Deploy (Dev)') {
            agent { label 'deploy' }
            steps {
                echo "Deploying Postgress DB"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run pre-deploy -- --pr=${CHANGE_ID} --env=dev"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run setup -- --pr=${CHANGE_ID} --env=dev"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run seed -- --pr=${CHANGE_ID} --env=dev"
            }
        }
        stage('Test API (Dev)') {
            agent { label 'deploy' }
            steps {
                echo "Testing app"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run test -- --pr=${CHANGE_ID} --env=dev"
            }
        }
        stage('Deploy (DEV/PR ENV) API and App') {
            agent { label 'deploy' }
            when {
                expression {
                    return env.CHANGE_TARGET != 'dev' && env.CHANGE_TARGET != 'staging' && env.CHANGE_TARGET != 'prod';
                }
            }
            steps {
                echo "Deploying API for ${CHANGE_ID}..."
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=dev"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy-tools -- --pr=${CHANGE_ID} --env=dev"
                echo "Deploying APP for ${CHANGE_ID}..."
                sh "cd app/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=dev"
            }
        }
        stage('Pre-Deploy (Dev) [Static]') {
            agent {
                label 'deploy'
            }
            when {
                environment name : 'CHANGE_TARGET', value: 'dev'
            }
            steps {
                echo "Deploying Postgress [STATIC] ..."
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run pre-deploy -- --pr=${CHANGE_ID} --env=dev --type=static"
                echo "Deploying backup app [STATIC]"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy-db-backup -- --pr=${CHANGE_ID} --env=dev --type=static"
                echo "Running DB Backup Job [STATIC]"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run backup -- --env=dev --backup=true"
                echo "Running DB Migration [STATIC]"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run setup -- --pr=${CHANGE_ID} --env=dev --type=static"
                echo "Running DB Seed Job [STATIC]"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run seed -- --pr=${CHANGE_ID} --env=dev --type=static"
            }
        }
        stage('Sonarqube') {
            agent {
                label 'deploy'
            }
            when {
                environment name : 'CHANGE_TARGET', value: 'dev'
            }
            steps {
                script {
                    echo "Running Sonarqube"
                    checkout scm
                    dir('.jenkins/sonarqube/sonar-runner') {
                        // sh "npm install typescript"
                        sh(returnStdout: true, script: "gradlew sonarqube -Dsonar.host.url=https://sonarqube-8ecbmv-tools.pathfinder.gov.bc.ca -Dsonar.projectKey=invasives-app -Dsonar.verbose=true --stacktrace --info")
                        sleep(30)
                        sh(returnStdout: true, script: "gradlew sonarqube -Dsonar.host.url=https://sonarqube-8ecbmv-tools.pathfinder.gov.bc.ca -Dsonar.projectKey=invasives-api -Dsonar.verbose=true --stacktrace --info")
                        sleep(30)
                        sh "oc extract secret/sonarqube-status-urls --to=${env.WORKSPACE}/sonar-runner --confirm"
                        SONARQUBE_STATUS_JSON = sh(returnStdout: true, script: "curl -w '%{http_code}' '${SONARQUBE_STATUS_URL}'")
                        SONARQUBE_STATUS = sonarGetStatus (SONARQUBE_STATUS_JSON)
                        if ( "${SONARQUBE_STATUS}" == "ERROR") {
                            echo "Sonarqube scan failed"
                            currentBuild.result = 'FAILURE'
                            exit 1
                        } else {
                            echo "Sonarqube scan passed"
                        }
                    }
                }
            }
        }
        stage('Deploy (Dev) API/APP [Static]') {
            agent {
                label 'deploy'
            }
            when {
                environment name : 'CHANGE_TARGET', value: 'dev'
            }
            steps {
                echo "Deploying API [dev] ..."
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=dev --type=static"
                echo "Deploying dev tools ..."
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy-tools -- --env=dev --type=static"
                echo "Deploying APP[dev] ..."
                sh "cd app/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=dev --type=static"
            }
        }
        stage('Pre-Deploy (Test)') {
            agent {
                label 'deploy'
            }
            when {
                environment name : 'CHANGE_TARGET', value: 'staging'
            }
            steps {
                echo "Deploying Postgress [TEST] ..."
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run pre-deploy -- --pr=${CHANGE_ID} --env=test --type=static"
                echo "Deploying backup of app [TEST]"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy-db-backup -- --pr=${CHANGE_ID} --env=test --type=static"
                echo "Running DB Backup Job [TEST]"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run backup -- --env=test --backup=true"
                echo "Running DB Migration [TEST]"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run setup -- --pr=${CHANGE_ID} --env=test --type=static"
                echo "Running DB Seed Job [TEST]"
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run seed -- --pr=${CHANGE_ID} --env=test --type=static"
            }
        }
        stage('Deploy (TEST) API/APP') {
            agent { label 'deploy' }
            when {
                environment name : 'CHANGE_TARGET', value: 'staging'
            }
            steps {
                echo "Deploying in [TEST] [API]..."
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=test --type=static"
                echo "Deploying in [TEST] [APP]..."
                sh "cd app/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=test --type=static"
                echo "Deploying dev tools [TEST] ..."
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy-tools -- --env=test --type=static"
            }
        }
        stage('Deploy (PROD) API/APP') {
            agent { label 'deploy' }
            when {
                environment name : 'CHANGE_TARGET', value: 'prod'
            }
            steps {
                script {
                    def IS_APPROVED = input(message: "Deploy to PROD?", ok: "yes", parameters: [string(name: 'IS_APPROVED', defaultValue: 'yes', description: 'Deploy to PROD?')])
                    if (IS_APPROVED != 'yes') {
                        currentBuild.result = "ABORTED"
                        error "User cancelled"
                    }
                    echo "Deploying Postgress [PROD] ..."
                    sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run pre-deploy -- --pr=${CHANGE_ID} --env=prod --type=static"
                    echo "Deploying backup of app [PROD]"
                    sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy-db-backup -- --pr=${CHANGE_ID} --env=prod --type=static"
                    echo "Running DB Backup Job [PROD]"
                    sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run backup -- --env=prod --backup=true"
                    echo "Running DB Migration [PROD]"
                    sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run setup -- --pr=${CHANGE_ID} --env=prod --type=static"
                    echo "Deploying in [PROD] [API]..."
                    sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=prod --type=static"
                    echo "Deploying in [PROD] [APP]..."
                    sh "cd app/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=prod --type=static"
                    echo "Deploying dev tools [PROD] ..."
                    sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy-tools -- --env=prod --type=static"
                } 
            }
            /*input {
                message "Should we continue with deployment to TEST?"
                ok "Yes!"
            }
            steps {
                echo "Deploying ..."
                sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run deploy -- --pr=${CHANGE_ID} --env=prod"
            }*/
        }
    }
}